### ISSUE TITLE
Run JCK without STF wrapper

### ISSUE THREAD

**Issue by Mesbah-Alam** [adoptium/aqa-systemtest#142]
Currently JCKs run via STF wrappers. These wrappers are part of systemtest repository. So, in order to compile and run JCKs we need to compile systemtests and STF, however JCKs have run without STF wrappers in the past. For sake of simplicity and maintenance we may want to think about running JCKs without the STF wrappers.

**Comment by lumpfish** [comment]
@Mesbah-Alam - please clarify

1.  - _"at the moment you can't get/compile STF without getting and compiling systemtests"_.  This is not true.  You can clone, make (and make test) the stf repository on its own.
2.  - _" JCKs don't need systemtests to be built"_.  This is also not true.  The Jck.java test automation (which requires the stf framework) resides in the openjdk-systemtest repository (on the basis that it is automation for java testing, whereas stf itself is test product agnostic (though it has actually only ever been used for java testing as far as I'm aware)).

There is a makefile in the openjdk-systemtest repository (on the same project as Jck.java (test,jck) which can be used to build the JCK native (C) test cases.  Without that you would have to build them manually.  If you just want to run the JCK without using the openjdk-systemtest automation (e.g. using the javatest GUI) then that is the only 'dependency'. 

What is the actual problem you have which you are trying to resolve?

**Comment by Mesbah-Alam** [comment]
@lumpfish 
Apology for a not-so-clear description. I have updated it. The issue was originally created with the following in mind:  JCK tests currently run via STF wrappers. These wrappers are part of systemtest repository. So, in order to compile and run JCKs we need to compile systemtests and STF. However JCKs have run without STF wrappers in the past. So, for sake of simplicity and ease of maintenance we may want to think about running JCKs without the STF wrappers.

**Comment by Mesbah-Alam** [comment]
Following steps should allow us to run JCK without STF: 
1. Extract logic from jck.java that generates jtb file. 
2. Invoke javaagent directly with the jtb file. 
3. Run JCK directly using command line to generate output in xml. 
4. Use stylesheet to convert output xml into junit format so that we can view individual failure output in jenkins.

**Comment by lumpfish** [comment]
See here for scripts to generate .jti files which can then be used to run the JCK either through the javatest GUI or the javatest command line tool supplied with the JCK.  Note also that AdoptOpenJDK is not currently running the JCK due to licensing issues.

**Comment by Mesbah-Alam** [comment]
This issue is now being tracked by backlog/issues/372
