### ISSUE TITLE
DirectByteBufferLoadTest fails on Linux aarch64 JDK11 hotspot

### ISSUE THREAD

**Issue by Mesbah-Alam** [adoptium/aqa-systemtest#180]
**Test failure output**
```
NLT testFailure: testFutureSequentialReadWriteMultiple(net.adoptopenjdk.test.nio2.asyncio.client.MultipleReadWriteFutureTest): Index -2147483648 out of bounds for length 17
NLT java.lang.ArrayIndexOutOfBoundsException: Index -2147483648 out of bounds for length 17
NLT 	at net.adoptopenjdk.test.nio2.util.RandomByteArrays.getRandomByteArray(RandomByteArrays.java:95)
NLT 	at net.adoptopenjdk.test.nio2.util.SendingMessage.setRandomMessage(SendingMessage.java:65)
NLT 	at net.adoptopenjdk.test.nio2.asyncio.client.MultipleReadWriteFutureTest.runFutureSequentialReadWriteMultiple(MultipleReadWriteFutureTest.java:200)
NLT 	at net.adoptopenjdk.test.nio2.asyncio.client.MultipleReadWriteFutureTest.testFutureSequentialReadWriteMultiple(MultipleReadWriteFutureTest.java:94)
NLT 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
NLT 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
NLT 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
NLT 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
NLT 	at junit.framework.TestCase.runTest(TestCase.java:176)
NLT 	at junit.framework.TestCase.runBare(TestCase.java:141)
NLT 	at junit.framework.TestResult$1.protect(TestResult.java:122)
NLT 	at junit.framework.TestResult.runProtected(TestResult.java:142)
NLT 	at junit.framework.TestResult.run(TestResult.java:125)
NLT 	at junit.framework.TestCase.run(TestCase.java:129)
NLT 	at junit.framework.TestSuite.runTest(TestSuite.java:252)
NLT 	at junit.framework.TestSuite.run(TestSuite.java:247)
NLT 	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
NLT 	at org.junit.runners.Suite.runChild(Suite.java:128)
NLT 	at org.junit.runners.Suite.runChild(Suite.java:27)
NLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
NLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
NLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
NLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
NLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
NLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
NLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
NLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
NLT 	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:129)
NLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:177)
NLT 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
NLT 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
NLT 	at java.base/java.lang.Thread.run(Thread.java:834)
```
**Test source Link:** 
https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/27eedf98c37b5c950ef3d0810aa01076284318df/openjdk.test.nio/src/test.nio/net/adoptopenjdk/test/nio2/util/RandomByteArrays.java#L95

**Test repo:** 
https://github.com/AdoptOpenJDK/openjdk-systemtest

**Build link**
https://ci.adoptopenjdk.net/job/openjdk11_hs_systemtest_aarch64_linux/1/tapResults/

* Note, the same test passes on other platforms (e.g. Linux x64: https://ci.adoptopenjdk.net/view/Test_system/job/openjdk11_hs_systemtest_x86-64_linux/16/tapResults/)

**Comment by Mesbah-Alam** [comment]
Note, NioLoadTest_0 fails due to the same isue too, https://ci.adoptopenjdk.net/job/openjdk11_hs_systemtest_aarch64_linux/1/tapResults/

**Comment by Mesbah-Alam** [comment]
Grinder link: https://ci.adoptopenjdk.net/view/work%20in%20progress/job/Grinder/201/console

Failure frequency: The test fails 2/5 times in a 5x grinder.

**Comment by Mesbah-Alam** [comment]
@karianna - this looks to be an issue in hotspot aarch64 Linux build. Could someone from hotspot team take a look at it?

**Comment by Mesbah-Alam** [comment]
Related issue: https://github.com/eclipse/openj9/issues/3933

**Comment by Mesbah-Alam** [comment]
Test excluded from arm and aix : https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/systemtest/otherLoadTest/playlist.xml#L132

**Comment by lumpfish** [comment]
I have confirmed that the `java.lang.OutOfMemoryError: native memory exhausted` still occurs on aarch64_linux and and ppc64_aix.

The test allocates DirectByteBuffers in the loop:
```
			for (i = 0; i < ITERATIONS; i++) {

				System.out.println("Iteration: " + i + " Total memory is: "
						+ r.totalMemory() + "Initial free memory: "
						+ r.freeMemory());
				bbStore[i] = ByteBuffer.allocateDirect(ALLOC_SIZE);
				// *** dereference to allow GC
				bbStore[i] = null;
			}
```
Although the reference to the byte buffer (on the java heap) is dereferenced I assume the underlying native memory is freed asynchronously and on the more constrained operating systems / hardware this might mean that more memory is allocated for a new buffer the next time through the loop before the previous buffer memory is freed.

In addition, the test is run in parallel with an nio workload, which also uses native memory.

I have used the stf.load setSuiteThinkingTime to cause the load test harness to wait 1 millisecond before starting a new test (the individual test cases are run repeatedly and on multiple threads) to allow more time for the native memory to be reclaimed.  The test now passes on the platforms (ppc64_aix and aarch64) it has been excluded from.

PR is https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/368

Merging this PR will not cause the test to start executing in the build pipelines- the playlist.xml file needs updating.  PR https://github.com/AdoptOpenJDK/openjdk-tests/pull/2013 reinstates the tests.  The tests should only be reinstated when / if this PR is merged.

**Comment by lumpfish** [comment]
Comment above says:

> Note, NioLoadTest_0 fails due to the same isue too, https://ci.adoptopenjdk.net/job/openjdk11_hs_systemtest_aarch64_linux/1/tapResults/

I will see if that test needs a similar fix.

**Comment by lumpfish** [comment]
I have run the NioLoadTest on 5 * Grinders on 5 machines each (so 25 runs across 5 machines per test) on the following nightly builds:

jdk8
openj9
aarch64 not supported
hotspot
aarch64_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4244/
arm_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4245/

jdk11
openj9
aarch64_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4217/
hotspot
aarch64_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4215/
arm_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4249/

jdk15
openj9
aarch64_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4248/
hotspot
aarch64_linux: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4246/

There were no failures seen.
On that basis I suggest the NioLoadTest be reenabled on arm.  If it goes out of memory again hopefully we will have some more current information to try to reproduce and investigate.

**Comment by lumpfish** [comment]
This test target has been renamed DBBLoadTest

**Comment by lumpfish** [comment]
Fixed by https://github.com/adoptium/aqa-systemtest/pull/368, https://github.com/AdoptOpenJDK/openjdk-tests/pull/2013, closing.
