### ISSUE TITLE
jdk 16, 17 --illegal-access change, JEP 396 Strongly Encapsulate JDK Internals by Default

### ISSUE THREAD

**Issue by pshipton** [adoptium/aqa-systemtest#386]
jdk16, 17 change the default of `--illegal-access=` from `permit` to `deny`.
JEP 396: Strongly Encapsulate JDK Internals by Default https://github.com/eclipse/openj9/issues/11240

See https://ci.eclipse.org/openj9/job/Grinder/1300/tapResults/ - extended.system (the sanity.system tests passed).
MiniMix_5min_0
```
LT  18:26:20.938 - Test failed
LT    Failure num.  = 1
LT    Test number   = 2974
LT    Test details  = 'Mauve[gnu.testlet.java.lang.reflect.AccessibleObject.accessible]'
LT    Suite number  = 0
LT    Thread number = 0
LT  >>> Captured test output >>>
LT  PASS: gnu.testlet.java.lang.reflect.AccessibleObject.accessible (number 0)
LT  java.lang.reflect.InaccessibleObjectException: Unable to make protected java.lang.ClassLoader() accessible: module java.base does not "opens java.lang" to unnamed module @20c80e7
LT  	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
LT  	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
LT  	at java.base/java.lang.reflect.Constructor.checkCanSetAccessible(Constructor.java:188)
LT  	at java.base/java.lang.reflect.Constructor.setAccessible(Constructor.java:181)
LT  	at gnu.testlet.java.lang.reflect.AccessibleObject.accessible.test(accessible.java:43)
LT  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
LT  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
LT  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
LT  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
LT  	at net.adoptopenjdk.loadTest.adaptors.MauveAdaptor.executeTest(MauveAdaptor.java:74)
LT  	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
LT  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
LT  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
LT  	at java.base/java.lang.Thread.run(Thread.java:853)
LT  FAIL: gnu.testlet.java.lang.reflect.AccessibleObject.accessible: java.lang.reflect.InaccessibleObjectException: Unable to make protected java.lang.ClassLoader() accessible: module java.base does not "opens java.lang" to unnamed module @20c80e7 (number 0)
```

HCRLateAttachWorkload_previewEnabled_0 also failed on this jdk17 build, but perhaps related to using a preview feature rather than --illegal-access

**Comment by pshipton** [comment]
Ah, HCRLateAttachWorkload_previewEnabled_0 needs a newer version of ASM which understands jdk17.

**Comment by Mesbah-Alam** [comment]
Updating ASM to the latest 9.0 fixes the `HCRLateAttachWorkload_previewEnabled_0`  test on JDk 16 (test run in internal Grinder/12786). 

ASM updated to 9.0 in the PRs of https://github.com/AdoptOpenJDK/openjdk-tests/issues/2125

**Comment by pshipton** [comment]
Not sure jdk16 was ever broken wrt ASM. The failure I got is with jdk17, I don't think there is any ASM version that supports that yet. This is fine, we can accept the failure for a short time, or exclude the test if it's causing triage problems.

**Comment by Mesbah-Alam** [comment]
I see. However, the ASM we were using was not being updated for a while. These PRs update ASM to the latest version--which can't hurt.

**Comment by Mesbah-Alam** [comment]
Hi @karianna - https://github.com/AdoptOpenJDK/openjdk-tests/issues/2125 doesn't solve this issue. It's only related. Re-opening it.

**Comment by pshipton** [comment]
See also https://github.com/eclipse/openj9/issues/11607

**Comment by Mesbah-Alam** [comment]
HCRLateAttachWorkload_previewEnabled_0 has been fixed for 17 and up: ( e.g. https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk17_j9_extended.system_ppc64_aix/49). This issue can be closed.
