### ISSUE TITLE
Augment system_custom command line with required add-opens option for JDK 9+

### ISSUE THREAD

**Issue by Mesbah-Alam** [adoptium/aqa-systemtest#418]
For running MiniMix target via `system_custom` on jdk 9+, user needs to provide `-add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED` option in `EXTRA_OPTIONS`. 

This can be automated by augmenting the command line with the required extra option when we are on JDK9+

**Comment by lumpfish** [comment]
How generic is this problem?  If every systemtest needs these extra arguments on jdkn+ (is it actually jdk16+?) then STF itself could add them to all java command lines and the playlists would not need to be changed.

**Comment by Mesbah-Alam** [comment]
The problem is not entirely generic so far. It has only been seen while running the MiniMix 5m test on JDK 16. Ref:  https://github.com/eclipse/openj9/issues/11607#issuecomment-756853554
