### ISSUE TITLE
jdk16 tests fail with "Try running with '--enable-preview'"

### ISSUE THREAD

**Issue by lumpfish** [adoptium/aqa-systemtest#448]
Test are failing in jck16 testing with messages similar to:
```
java.lang.UnsupportedClassVersionError: Preview features are not enabled for javasoft/sqe/tests/vm/jvmti/rdef001/rdef00104/rdef00104 (class file version 60.65535). Try running with '--enable-preview'
```

Looks like the problem is this code in https://github.com/adoptium/aqa-systemtest/blob/master/openjdk.test.jck/src/test.jck/net/adoptopenjdk/stf/Jck.java which does not cover JCK16:
```
			if (jckVersion.contains("jck12") || jckVersion.contains("jck13")) {
				extraJvmOptions += " --enable-preview";
			}
```

**Comment by smlambert** [comment]
This is handled by https://github.com/adoptium/aqa-tests/pull/2823 which should get merged soon, but I can regenerate the job from that branch right now (which I though I had done, but possibly missed some platforms, is this AIX?)

**Comment by smlambert** [comment]
https://ci.eclipse.org/temurin-compliance/view/Grinder/job/Test_Job_Auto_Gen/39/ AIX jdk16 jobs regenerated with --enable-preview

**Comment by Mesbah-Alam** [comment]
This issue is resolved, closing.
