### ISSUE TITLE
net.adoptopenjdk.test.bigdecimal needs adjusting for jdk20+

### ISSUE THREAD

**Issue by jiekang** [adoptium/aqa-systemtest#482]
Deep history shows consistent failures in bigdecimal for jdk 20:

https://trss.adoptium.net/deepHistory?testId=640da3e717052c6715411dd9

Examining three of those failures, I noticed in the sources there is a if-case separating jdk version 13+:

E.g. https://github.com/adoptium/aqa-systemtest/blob/0eb9f57f198fe194c070295c261e8bafeaed08aa/openjdk.test.math/src/test.math/net/adoptopenjdk/test/bigdecimal/TestSuite017.java

Then looking at BigDecimal sources, I noticed a change for jdk20 that suggests we should expect the behavior in jdk20 to match jdk11 again:

Latest commit of file: https://github.com/openjdk/jdk20/blob/master/test/jdk/java/math/BigDecimal/MovePointTests.java
Points to: https://bugs.openjdk.org/browse/JDK-8289260

This matches all three test cases I examined which failed when testing `movePointLeft` or `movePointRight`

I did not look deeply at every single failure in the deep history though; the failures are a different test case in every run which is curious;  I guess the order of tests is random. Does it fail-fast?

**Comment by sophia-guo** [comment]
Close by #483
